In [56]:
import tensorflow as tf

### 텐서플로우 행렬의 표현

In [57]:
input_data = [
    [1,1,1],[2,2,2]
]

In [58]:
x = tf.placeholder(dtype = tf.float32, shape=[2,3])
w = tf.Variable([[2],[2],[2]], dtype= tf.float32)
b = tf.Variable([4], dtype= tf.float32)
y = tf.matmul(x,w) + b

##### 텐서플로우에서 행렬의 곱은 일반 * 을 사용하지 않고, 텐서 프롤우 함수 tf.matmul() 을 사용한다.

In [7]:
x.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [11]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict={x:input_data})
print(result)

[[10.]
 [16.]]


## 텐서플로우에 행렬 차원 용어
### 행렬이 아닌 숫자나 상수 0차원 : 스칼라 Scalar
### 1차원행렬 : 백처 Vector
### 2차원행렬 : 매크릭스 Matrix
### 3차원행렬 : 3-Tensor 또는 큐브
### 그 이상의 다차원 행렬 : n-Tensor

## resuce_sum

In [12]:
x = [[1,1,1],
    [1,1,1]]

In [27]:
tf.rank(x).eval(session = sess) # rank = 차원수, eval = output === 차원수 2

2

In [34]:
tf.reduce_sum(x, axis = [0,1]).eval(session = sess)

# axis 파라미터는 제거할 축
# resuce all dim 천체 합을 구하라 (1+1+1+1+1+1 = 6)
# 그 결과 모든 차원이 제거되고 단 하나의 스칼라 값이 출력됨

6

In [35]:
tf.reduce_sum(x, axis=1).eval(session = sess)
# 1 인덱스 차원을 제거하고 , 0 인덱스 차원에 합해라.

array([3, 3])

In [36]:
tf.reduce_sum(x, axis=1, keepdims = True).eval(session = sess)
# 1 인덱스 차원을 제거하고 , 0 인덱스 차원에 합해라.
# keepdims 는 결과를 얻고 최초 차원을 유지해라.

array([[3],
       [3]])

## reduce_mean


In [49]:
x = [[2.,2.],[3.,3.]]

In [54]:
tf.reduce_mean(x).eval(session = sess)
# redece all dim 전체 평균을 구한다 (2+2+3+3) / 4 = 2.5

2.5